import uudised.Article
import uudised.User

class BootStrap {

    def init = { servletContext ->
		
		if (!Article.count()) {
			
			new User(login: "autor", password: "autor", firstName: "autor", lastName: "autor").save(failOnError:true)
			new Article(title: "Obama pushes Putin on Crimea talks", descriptionShort: "US President Obama urges diplomacy in a telephone call with Russia's President Putin",descriptionLong: "US President Obama urges diplomacy in a telephone call with Russia's President Putin, who says the Ukraine crisis should not damage relations.", content: "The Russian president told Mr Obama Moscow could not ignore calls for help from Russian speakers, but that ties with the US should not be affected. Crimean MPs have asked to join Russia and called a referendum on the move. The Ukrainian Paralympic team has confirmed it will not boycott the Sochi Winter Paralympics. The head of the team, Valeriy Sushkevich, said they would participate but had asked President Putin that before and during [the Games] there will be peace. The Games, which open in the Russian Black Sea resort later on Friday, has already been boycotted by many foreign dignitaries amid international tensions over Russia's military intervention in Crimea.",priority: "3",views: 20000, author: User.findByLogin("autor")).save(failOnError:true)
			new Article(title: "Putin pushes Obama on Crimea talks", descriptionShort: "US President Obama urges diplomacy in a telephone call with Russia's President Putin",descriptionLong: "US President Obama urges diplomacy in a telephone call with Russia's President Putin, who says the Ukraine crisis should not damage relations.", content: "The Russian president told Mr Obama Moscow could not ignore calls for help from Russian speakers, but that ties with the US should not be affected. Crimean MPs have asked to join Russia and called a referendum on the move. The Ukrainian Paralympic team has confirmed it will not boycott the Sochi Winter Paralympics. The head of the team, Valeriy Sushkevich, said they would participate but had asked President Putin that before and during [the Games] there will be peace. The Games, which open in the Russian Black Sea resort later on Friday, has already been boycotted by many foreign dignitaries amid international tensions over Russia's military intervention in Crimea.",priority: "3",views: 20000, author: User.findByLogin("autor")).save(failOnError:true)
			new Article(title: "Vahur pushes Putin on Crimea talks", descriptionShort: "US President Obama urges diplomacy in a telephone call with Russia's President Putin",descriptionLong: "US President Obama urges diplomacy in a telephone call with Russia's President Putin, who says the Ukraine crisis should not damage relations.", content: "The Russian president told Mr Obama Moscow could not ignore calls for help from Russian speakers, but that ties with the US should not be affected. Crimean MPs have asked to join Russia and called a referendum on the move. The Ukrainian Paralympic team has confirmed it will not boycott the Sochi Winter Paralympics. The head of the team, Valeriy Sushkevich, said they would participate but had asked President Putin that before and during [the Games] there will be peace. The Games, which open in the Russian Black Sea resort later on Friday, has already been boycotted by many foreign dignitaries amid international tensions over Russia's military intervention in Crimea.",priority: "3",views: 20000, author: User.findByLogin("autor")).save(failOnError:true)
			new Article(title: "Peeter pushes Putin on Crimea talks", descriptionShort: "US President Obama urges diplomacy in a telephone call with Russia's President Putin",descriptionLong: "US President Obama urges diplomacy in a telephone call with Russia's President Putin, who says the Ukraine crisis should not damage relations.", content: "The Russian president told Mr Obama Moscow could not ignore calls for help from Russian speakers, but that ties with the US should not be affected. Crimean MPs have asked to join Russia and called a referendum on the move. The Ukrainian Paralympic team has confirmed it will not boycott the Sochi Winter Paralympics. The head of the team, Valeriy Sushkevich, said they would participate but had asked President Putin that before and during [the Games] there will be peace. The Games, which open in the Russian Black Sea resort later on Friday, has already been boycotted by many foreign dignitaries amid international tensions over Russia's military intervention in Crimea.",priority: "3",views: 20000, author: User.findByLogin("autor")).save(failOnError:true)
			
		}
		
    }
    def destroy = {
    }
}
